package com.example.healthcareproject.present.navigation

interface MainNavigator {
    fun navigateToHeartRate()
    fun navigateToOxygen()
    fun navigateToEcg()
    fun navigateToWeight()
    fun navigateBackToHomeFromHeartRate()
    fun navigateToNotificationFromHeartRate()
    fun navigateBackToHomeFromOxygen()
    fun navigateToNotificationFromOxygen()
    fun navigateToAddMedication()
    fun navigatePillFragmentToMedicalHistoryDetail(visitId: String)
    fun navigateMedicineToMedicalHistoryDetail(visitId: String)
    fun navigateToAddAppointment()
    fun navigateToAddMedicalVisit()
    fun navigateBackToMedicineFromAddAppointment()
    fun navigateBackToMedicineFromMedicalHistoryDetail()
    fun navigateBackToMedicineFromAddMedicalVisit()
    fun navigateToHeartRateFromNotification()
    fun navigateToOxygenFromNotification()
    fun navigateToEcgFromNotification()
    fun navigateToWeightFromNotification()
    fun navigateToTheme()
    fun navigateToEmergency()
    fun navigateToInformation()
    fun navigateToChangePassword()
    fun navigateBackToSettingsFromTheme()
    fun navigateBackToSettingsFromInformation()
    fun navigateBackToSettingsFromEmergency()
    fun navigateBackToSettingsFromChangePassword()
}